repos:
  - repo: "local"
    hooks:
    - id: "codechecks"
      name: "codechecks"
      stages: ["pre-push"]
      language: "system"
      files: ".py$"
      entry: "tox -e codechecks"
      pass_filenames: false
