sudo: true
os:
 - "linux"
 - "osx"
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
  - "pypy"
before_install:
  - sh -c set
  - git config --global user.email "travis-tahoe@tahoe-lafs.org"
  - git config --global user.name "Travis Tahoe"
  - git fetch --depth=1000
  - python misc/build_helpers/show-tool-versions.py
install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then echo installing on osx...; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update && brew install python; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=/usr/local/bin:$PATH; fi
  - echo $PATH; which python
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo pip install coveralls tox; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then pip install coveralls tox; fi
script:
  - tox -e coverage
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
matrix:
  allow_failures:
    - python: "pypy"
  fast_finish: true
