sudo: false
language: python
python:
  - "2.7"
  - "pypy"
before_install:
  - sh -c set
  - git config --global user.email "travis-tahoe@tahoe-lafs.org"
  - git config --global user.name "Travis Tahoe"
  - git fetch --depth=1000
  - python misc/build_helpers/show-tool-versions.py
install:
  - pip install coverage coveralls
before_script: pip install -e .
script: tahoe @coverage run --branch --source=src/allmydata @tahoe --version-and-path debug trial --rterrors --reporter=timing
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
matrix:
  allow_failures:
    - python: "pypy"
  fast_finish: true
