language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - sh -c set
  - git pull --depth=1000
  - python misc/build_helpers/show-tool-versions.py
install:
  - pip install 'twisted>=0.13.0'
  - pip install 'coveralls==0.4.2'
before_script: python setup.py build
script: bin/tahoe @coverage run --branch --source=src/allmydata @tahoe --version-and-path debug trial --rterrors --reporter=timing
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
