sudo: false
os:
 - "linux"
 - "osx"
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
before_install:
  - sh -c set
  - git config --global user.email "travis-tahoe@tahoe-lafs.org"
  - git config --global user.name "Travis Tahoe"
  - git fetch --depth=1000
  - python misc/build_helpers/show-tool-versions.py
install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then echo installing on osx...; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install python; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=/usr/local/bin:$PATH; fi
  - pip install coverage coveralls
before_script:
  - env
  - which python && python --version
  - pip install --upgrade pip
  - pip install -e .
script:
  - coverage run --branch --source=src/allmydata `which tahoe` --version-and-path debug trial --rterrors --reporter=timing
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
matrix:
  allow_failures:
    - python: "pypy"
  fast_finish: true
